# app.yaml - Simplified for Automatic Auth
name: ecomm-ai-data-agent
command: [
  "sh",
  "-c",
  "streamlit run app.py --server.address=0.0.0.0 --server.port=$PORT"
]
# We remove the 'env' section for DATABRICKS_HOST because the 
# App environment provides this automatically to the SDK